@startuml v3
title Version 3 - Arquitectura del alquiler

object Persona {
  nombre
  DNI
  telefono
  ingresos
}
object Arrendador {
  numeroInmuebles
}
object Inquilino {
  email
}
object ContratoAlquiler {
  tipoAlquiler
  vigencia
  fecha
}
object Inmueble {
  fechaCompra
  reformado
  tamaño
  direccion
}
object Mensualidad {
  cuantia
  fechaLimite
}
object Gastos {
  ibi 
  comunidad
  extras
}
object Impuestos {
  total
  pagado
  deducciones
}
object Beneficio {
  total
}

Persona --> Arrendador : es
Persona --> Inquilino : es
Arrendador --> Inmueble : tiene
Arrendador --> ContratoAlquiler : redacta
Inquilino --> ContratoAlquiler : firma
ContratoAlquiler --> Inmueble : alquila
Inquilino --> Mensualidad : paga
Mensualidad --> Impuestos : paga
Inmueble --> Gastos : tiene
Gastos -> Impuestos : deduce
Mensualidad --> Beneficio : genera
Beneficio -up-> Arrendador : otorga

@enduml