@startuml v2
title Version 2 - Arquitectura del alquiler

object Persona
object Arrendador
object Inquilino
object Contrato
object Inmueble
object Mensualidad
object Gastos
object Impuestos
object Beneficio

Persona --> Arrendador : es
Persona --> Inquilino : es
Arrendador --> Inmueble : tiene
Arrendador --> Contrato : redacta
Inquilino --> Contrato : firma
Contrato --> Inmueble : alquila
Inquilino --> Mensualidad : paga
Mensualidad --> Impuestos : paga
Inmueble --> Gastos : tiene
Gastos -> Impuestos : deduce
Mensualidad --> Beneficio : genera
Beneficio -up-> Arrendador : otorga

@enduml